CREATE TABLE news
(
    news_id   INTEGER NOT NULL,
    source_id BIGINT,
    CONSTRAINT pk_news PRIMARY KEY (news_id)
);

CREATE TABLE news_topics
(
    news_id  INTEGER NOT NULL,
    topic_id BIGINT  NOT NULL,
    CONSTRAINT pk_news_topics PRIMARY KEY (news_id, topic_id)
);

CREATE TABLE sources
(
    source_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name      VARCHAR(255),
    CONSTRAINT pk_sources PRIMARY KEY (source_id)
);

CREATE TABLE topics
(
    topic_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name     VARCHAR(255),
    CONSTRAINT pk_topics PRIMARY KEY (topic_id)
);

ALTER TABLE news
    ADD CONSTRAINT FK_NEWS_ON_SOURCE FOREIGN KEY (source_id) REFERENCES sources (source_id);

ALTER TABLE news_topics
    ADD CONSTRAINT fk_newtop_on_news FOREIGN KEY (news_id) REFERENCES news (news_id);

ALTER TABLE news_topics
    ADD CONSTRAINT fk_newtop_on_topic FOREIGN KEY (topic_id) REFERENCES topics (topic_id);